version: "3.9"

services:
  api:
    image: gtfs-manager-api:dev   # <— DODANE
    build:
      context: ./backend/gtfs-manager
      dockerfile: Dockerfile
    container_name: gtfs-manager-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5089
      Gtfs__DataDir: /app/Data
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5089:5089"
    volumes:
      - ./backend/gtfs-manager:/src
      - ./backend/gtfs-manager/Data:/app/Data
    working_dir: /src
    command: ["dotnet","watch","run","--urls","http://0.0.0.0:5089"]
    networks: [appnet]

  web:
      image: node:20-alpine
      container_name: gtfs-front
      working_dir: /app
      environment:
        VITE_API_URL: "http://localhost:5089"
      ports:
        - "5173:5173"
      volumes:
        - ./front:/app
        - /app/node_modules
      command: sh -c "npm ci --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 5173"
      depends_on:
        - api
      networks: [appnet]

networks:
  appnet:
    driver: bridge
