version: "3.9"

services:
  api:
    build:
      context: ./backend/gtfs-manager
      dockerfile: Dockerfile
    container_name: gtfs-manager-api
    environment:
      # stały port dev
      ASPNETCORE_URLS: http://0.0.0.0:5089
      # gdzie w kontenerze znajdują się pliki GTFS (real-time / static)
      Gtfs__DataDir: /app/Data
    ports:
      - "5089:5089"
    volumes:
      # hot-reload: kod + Data/ z hosta
      - ./backend/gtfs-manager:/src
      - ./backend/gtfs-manager/Data:/app/Data
    working_dir: /src
    command: [ "dotnet", "watch", "run", "--urls", "http://0.0.0.0:5089" ]
    networks:
      - appnet

  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: gtfs-front
    environment:
      # URL backendu widoczny z przeglądarki (hosta)
      VITE_API_URL: "http://localhost:5089"
      # niektóre bundlery czytają też odczyt z .env – patrz niżej
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173" ]
    networks:
      - appnet
    depends_on:
      - api

networks:
  appnet:
    driver: bridge
